### ISSUE TITLE
dev/api/search not working properly

### ISSUE THREAD

**Issue by andreafdaf** [agilecrm/rest-api#13]
Hi, I'm sending the following request:

```
{ 
  path: '/dev/api/search',
  headers: { Accept: 'application/json' },
  method: 'GET',
  query: 'q=andreafdaf%40gmail.com&page_size=1&type=PERSON',
  host: 'my_host.agilecrm.com',
  port: 443,
  auth: '_:_'
}
```

but I'm receiving a status 500 and an empty response, what's wrong?

**Comment by graut** [comment]
Hi,

Please check the URL generated by your code is equivalent to below URL or not ?

https://jsonwoodlif.agilecrm.com/dev/api/search?q=andreafdaf@gmail.com&page_size=1&type=PERSON

We tested and it is working for us. 500 error you are getting because you are not sending correct format. We tested with Rest Advance Client and it is working.
Tested url. http://snag.gy/TRJAd.jpg

**Comment by andreafdaf** [comment]
but this is wrong, when urlencoded the @ symbol becomes %40

the url should be: https://jsonwoodlif.agilecrm.com/dev/api/search?q=andreafdaf%40gmail.com&page_size=1&type=PERSON

**Comment by ranjanagilecrm** [comment]
Hi,

I think that's how it's supposed to work.  The receiving end is supposed to decode the @ symbol.
Ultimately, it depends on what the server expect. 

The recipient should be able to decode that automatically. Probably you need to use something such as URLDecoder.decode(url)  on your server side so that you can convert the %40 back to @ symbol.

Please contact Agile CRM Help Desk in case you need further information.

**Comment by andreafdaf** [comment]
@ranjanagilecrm you got what I said the other way around... it's your end that needs to convert %40 back to @, since by convention when sending URL params the params should be, well, URL-encoded

If you tell me "that's how it's supposed to work" I tell you... mmmm, no! I'm sending you a correctly formatted URL-encoded param, you are returning an empty 500 response, that's not right in any way :)
