### ISSUE TITLE
Getting 500 Server error on PUT contacts

### ISSUE THREAD

**Issue by clintonskakun** [agilecrm/rest-api#15]
Getting an obscure error from the API when trying to update a contact. This is driving me nuts. All of the fields are the correct types in json in a --data '{"id": 1233445}' type deal in curl.

Why am I not getting a better error message? Not like this just happened because of a server overload. I do all kinds of other calls before doing the update. Some updates pass, and a few fail, really simple ones that I'm confirming have the correct field info.

**Comment by clintonskakun** [comment]
BTW I'm using 

' -H "Content-Type: application/json; charset=UTF-8" ' ..
    ' -H "Accept: application/json" ' ..

it has -X PUT

and I've tried getting from a file like --data "@./my_file.json" and so on

**Comment by andreafdaf** [comment]
:+1: I'm having this same issue

**Comment by clintonskakun** [comment]
Still haven't found an answer to this. I eventually stopped getting the error. I think it may have had something to do with a bad id. However it slip through somewhere and create an error on the server.

**Comment by graut** [comment]
Hi @clintonskakun and @andreafdaf 

You might get 500 server error for wrong format of input or  else server was not able to load data properly.

We are under process to resolve this kind of issue to aware developer with status code and message so they can take proper action.

Note : We have added 3 methods to API for developer this will defiantly help you while updating contact or companies.We will shortly add this to docs also.

1. Partial update: Properties (contact/ company)
Issue with current update contact api : You need to send all data related to contact you are going to update, Not only the json data you want to update otherwise you will lose remaining data.

Solution : Partial update properties of contact/companies

Example : http://snag.gy/FoVJx.jpg

2.Partial update: Update Star :Update companies/contacts star value by id and star value

Example : http://snag.gy/fp8f5.jpg

3.Partial update: Update score: Update lead score for contact only by contact id and lead_score only

http://snag.gy/sfNGt.jpg

Note : Recommended for developer who want to update contact without losing any data.

Note : We are going to add few more APIs for developer this are mention below.

Add tags to contact/company by id.
Update Deal Partial.
Update Task Partial.
Update Note Partial..
Error message and error code. for each API

Please contact Agile CRM help desk if you need more info.

Thanks

**Comment by andreafdaf** [comment]
@clintonskakun it eventually stopped for me also, lasted for some weeks from half of September (more or less), then it never happened again as it never happened before, using the same code and the same ids (and now I see you've posted on Sep 27)

@graut the strange thing is that the SAME call sometimes passed and other times didn't

**Comment by clintonskakun** [comment]
@andreafdaf yeah that was around the time I was getting those errors as well. Later got actual error messages and found the problem. I was referencing incorrect data in the contacts. All fixed now. Seems to work great.

@graut The more the better. Making it API more developer friendly helps us build better integrations for customers.

**Comment by clintonskakun** [comment]
I don't seem to be getting this any more. Anyone else with the same error still happening feel free to open this up again (if you can, not sure extactly how the ticket works)
