### ISSUE TITLE
How do you update a company's properties?

### ISSUE THREAD

**Issue by tachang** [agilecrm/rest-api#16]
This does not work:

```
    payload = {
        'id': contact_id,
        'tags': tags,
        'type': "COMPANY",
        'properties': [
                {
                    "type": "SYSTEM",
                    "name": "website",
                    "subtype": "URL",
                    "value": website
                }
        ]
    }

```

**Comment by andreafdaf** [comment]
hi @tachang 

for this to work I do the following (all wrapped as a single function to make life simpler):
- 'GET', '/dev/api/contacts/'+contact_id
then using the "contact" i get back
- 'GET', '/dev/api/contacts/'+contact.contact_company_id
then I manipulate this object, which is the "company", since updating blindly sometimes created some issues, then
- 'PUT', '/dev/api/contacts', company

in other simpler ways I found that lots of updates go missing, they are accepted but don't change the data, or worse sometimes data gets corrupted (for example never EVER send an empty custom field, doing this caused the old interface to freeze when viewing the contact and I don't want to try again with the new one :grin: )

if you want to manipulate tags, also here don't try to update them in the contact object (doing this might cause the tags to be visible only in the list view, disappearing in the "show contact" view)
try to use:
- 'POST', '/dev/api/contacts/email/tags/add' or '/dev/api/contacts/email/tags/delete'

if you have contacts without emails I suggest you tu use e.g. "{{contact_id}}@something.com" as default email address since having the email is really important for some operations to be done in a simpler way

**Comment by graut** [comment]
Hi @tachang and @andreafdaf ,

We have added new API today to update contact partially. Here you don't need to send all data related to contact to just update required data.

If you know Advance Rest Client tool you easily understand from below image how to update company properties.

http://snag.gy/dJOpy.jpg

Any way we are going to update 3 API for now in docs:

1. Update contact/company properties (You need to pass only contact/company id and corresponding properties) as in above example we have seen.
 In the image we are updating company so we need company id and company properties.

http://snag.gy/dJOpy.jpg

2. edit star value : Update companies/contacts star value by id and star value
http://snag.gy/fp8f5.jpg

3. lead score : Update lead score for contact only by contact id and lead_score only
http://snag.gy/sfNGt.jpg

Note : We are going to add few more APIs for developer this are mention below.

1. Add tags to contact/company by id.
2. Update Deal Partial.
3. Update Task Partial.
4. Update Note Partial..
5. Error message and error code. for each API

Please contact agile crm help desk if you need more info.

Thanks

**Comment by ranjanagilecrm** [comment]
Please contact Agile CRM Help Desk if you need more info.
