### ISSUE TITLE
Error handling new contact creation

### ISSUE THREAD

**Issue by ernho** [agilecrm/rest-api#28]
Inserting new contact throws 

status: '500',
  'exception message': 'java.lang.NumberFormatException: For input string: "580085ebf992e33126523d80"' }

This was my fault because we tried to insert new user with our internal database id`s. 

First we are suprised that you use only number as so we guess you use sql but we are working with no-sql databases and can now not use same ids in your system as we use it on our. 

But back to the topic your error handling is bad. Why are you passing a java exception back to the client

**Comment by graut** [comment]
Hi @ernho,

Sorry for inconvenience caused due to error handling mechanism. For third party API we are dealing with status code only. Recently we have added message too for better understanding if customer is missing any thing. Due to the fact that we want API response fast we are not manipulating message for 500 server error. We are also requesting user to pass exactly the JSON data Agile CRM looking for. 

We are using Google cloud no-sql. 

For creating contact, task, deal we are generating unique ID and it won't be override. But if you want your ID also to be used then you have to use it as custom filed. We have custom field filter too so you can use your unique ID in future.

Please let us know if above information is helpful. Please contact Agile CRM support team in case need further help.

Thanks
