### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by andreafdaf** [agilecrm/rest-api#9]
- At the beginning of section 1 it is stated:
    "Tag name should start with an alphabet and can not contain special characters other than underscore and space."
- While in "Acceptable request representation" it reads:
    "tags": ["Lead","Likely Buyer","You_can-user $special chars"]

A clear contradiction!

**Comment by graut** [comment]
Working as expected the documentation now.
1.8 Adding Tags to a contact based on Email:(https://github.com/agilecrm/rest-api#18-adding-tags-to-a-contact-based-on-email)
URL used:
https://{domain}.agilecrm.com/dev/api/contacts/email/tags/add
We have tried to add below tags
 "tags": ["Lead","Likely Buyer","You_can-user $special chars"]
We are not able  to add tags because  "Tag name should start with an alphabet and can’t contain special characters other than underscore and space".

And tested some valid and invalid tags.
Tested Valid tags
1. ["Lead","Likely Buyer"]
2. ["Lead12","Likely Buyer"]
3. ["Lead","Likely 12 Buyer"]
4. ["Le_ad","Likely 12 Buyer"]
Tested Invalid tags
1. ["1Lead","Likely Buyer"]
2. ["_Lead", "Likely Buyer"]
3. ["Lead#", "Likely Buyer"]
4. ["!Lead"]

**Comment by andreafdaf** [comment]
I guess people at Agile don't really like to interact with GitHub, the DOC was updated since I opened this issue, I'll close it :)
